### ISSUE TITLE
usePalette is not exported and docs typos

### ISSUE THREAD

**Issue by estevanmaito** [jonyw4/color-thief-react#53]
I'll try to PR, but I'll add this here so I don't forget:

### Format

- `rgbToString` is actually `rgbString`
- `rgbToArray` is actually `rgbArray`

### usePalette

It's not exported https://github.com/jonyw4/color-thief-react/blob/master/src/index.js#L7

### Package

The production build contains src and test code and could be optimized.

**Comment by jonyw4** [comment]
Good points and thanks a lot @estevanmaito. I am looking forward for this PR!
I am going to update this repo to typescript too, I am planning to that in this month

**Comment by jonyw4** [comment]
I update this repo. I fix all these errors, refactored some parts of code and change the project to typescript. Please, use after `v2.0.4` version. Enjoy! 😁
