### ISSUE TITLE
Bug with the hook proccess

### ISSUE THREAD

**Issue by hpachy** [jonyw4/color-thief-react#93]
Hello I tried to use you color-thief-react but I still have this annoying error about react rules...
>Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
>1. You might have mismatching versions of React and the renderer (such as React DOM)
>2. You might be breaking the Rules of Hooks
>3. You might have more than one copy of React in the same app
>See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

<img width="1273" alt="Capture d’écran, le 2020-11-09 à 11 08 29" src="https://user-images.githubusercontent.com/24634810/98528164-38d98280-227c-11eb-9d20-5dc38c7bd277.png">

I wonder if you can help me to understand what's going on ....

I'm on react 17 and I'm using typeScript

**Comment by JoakimThorne** [comment]
Same problem but with react": "^16.12.0",

**Comment by jonyw4** [comment]
Hi guys, I don't know why this is happening. I need to make some tests and look more closely for bugs. 🔍
For now, I asked for you to make some demo project where this bug happens. Maybe in CodeSandbox or another similar tool. 
@hpachy and @JoakimThorne.

This will advance our work and keep everyone in the same context. Thanks for report this error 🙏

**Comment by hpachy** [comment]
quite old but that'was my use case : https://codesandbox.io/s/color-thief-react-forked-guk92

**Comment by jonyw4** [comment]
Thanks I will take a look in the next days. Fell free to propose a solution 😄

**Comment by JoakimThorne** [comment]
Hi,

Like I said before (maybe I wasnt clear). 
But if you step "color-thief-react": "2.0.10", to "color-thief-react": "2.0.11" it will work since 2.0.11 includes react 17.
_2.0.11 (2020-12-15)
Bug Fixes
deps: update react monorepo to v17 (84bb935)_

**Comment by pklada** [comment]
We're running into this error as well

**Comment by pklada** [comment]
Any luck with this one?

**Comment by pklada** [comment]
Ok sorry, final follow up, implementing this fix: https://github.com/facebook/react/issues/13991#issuecomment-435587809 fixed the issue for me, so it was definitely related to multiple instances of react in the same bundle. 

running `npm ls react` showed react 17 as part of this package, and our project uses 16.4. Not sure how to fix this on this package's end, but maybe opt to rely on the parent project's react instance rather than bundle?

**Comment by jonyw4** [comment]
Hi @pklada I just released  `2.0.12-beta.1` moving `react` and `react-dom` to `peerDependancies`. Can you try and give me some feedback if that works for you?

**Comment by jonyw4** [comment]
@JoakimThorne @hpachy 
I created a fork of @hpachy CodeSandox using `2.0.12-beta.1` release and seems to resolve the problem. Can you try for me and give some feedback? If this resolve the issue I will merge and publish a new  official release

https://codesandbox.io/s/color-thief-react-forked-gqb1t
